[build]
  # 指定前端构建目录
  publish = "frontend/build"
  # 构建命令 - 使用正确的Linux语法
  command = "cd frontend && npm install && npm run build"

[build.environment]
  # Node.js版本
  NODE_VERSION = "18"
  # 设置环境变量 - 使用正确的语法
  NODE_OPTIONS = "--openssl-legacy-provider"

# 重定向规则 - 支持React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 处理API请求 - 重定向到后端
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-domain.com/api/:splat"
  status = 200
  force = true

# 静态资源缓存
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# 安全头
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
