# Netlify配置文件
[build]
  # 发布目录（当前目录）
  publish = "."
  
[build.environment]
  # Node.js版本
  NODE_VERSION = "18"

# 重定向规则
[[redirects]]
  # 根路径直接进入 app.html
  from = "/"
  to = "/app.html"
  status = 200

[[redirects]]
  # 单页应用支持
  from = "/*"
  to = "/app.html"
  status = 200

# 允许直接访问写作模块的独立页面与资源
[[redirects]]
  from = "/src/writing-module/*"
  to = "/src/writing-module/:splat"
  status = 200
  
# 头部设置
[[headers]]
  for = "/*"
  [headers.values]
    # 安全头部
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # 缓存控制
    Cache-Control = "public, max-age=31536000"
    
# 静态文件缓存
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"